version: '3.7'

services:
  app:
    build: .
    volumes:
      - ./codes:/home/rstudio/codes
      - ./outputs:/home/rstudio/outputs
      - ./misc:/home/rstudio/misc
    environment:
      PASSWORD: passwd
    ports:
      - "80:8787"
